"""Контракты Autogenerator: модели данных и интерфейсы, через которые общаются модули.

Пакет не содержит логики обработки и не зависит от других модулей приложения.
"""

from .errors import AgenError, ErrorCode
from .history import CoverageCell, CoverageReport, CoverageState, HistoryManifest, HistoryProvider, UploadRef
from .jobs import IngestRequest, IngestResult, RunRequest
from .periods import DateSpan, Period, PeriodUnit
from .plugins import (
    ENTRY_POINT_GROUPS,
    PLUGIN_API_VERSION,
    AggregationPlugin,
    BlockContext,
    BlockData,
    BlockPlugin,
    BlockTarget,
    DataNeeds,
    ExpressionTools,
    NoParams,
    ParamsPlugin,
    Plugin,
    PluginInfo,
    PluginKind,
    PluginManifest,
    PluginStatus,
    ProgressCallback,
    ReaderPlugin,
    ReadProgress,
    SampleTable,
    StepContext,
    StepPlugin,
    WindowPlugin,
)
from .results import (
    EngineResult,
    Issue,
    IssueLevel,
    NodeKind,
    NodeState,
    NodeStatus,
    RenderResult,
    RunResult,
)
from .scenario import (
    SPEC_VERSION,
    AggregateSpec,
    BlockSpec,
    DatasetSpec,
    GroupBySpec,
    InputSpec,
    MetricSpec,
    ScenarioSpec,
    SlideSpec,
    SortSpec,
    StepSpec,
    WindowSpec,
)
from .snapshot import (
    CastIssue,
    ColumnProfile,
    ColumnSnapshot,
    ReconcileResult,
    ReconcileStatus,
    SchemaSnapshot,
    UploadResult,
    UploadStatus,
    ValueCount,
)
from .sources import ColumnSpec, DType, OverlapPolicy, PeriodFrom, ReadOptions, SourceSpec
from .storage import (
    DEFAULT_WORKSPACE,
    BlobStore,
    MetadataStore,
    SourceRecord,
    SourceVersionRecord,
    UploadRecord,
)
from .theme import (
    Geometry,
    LayoutInfo,
    LayoutRole,
    PlaceholderInfo,
    RoleBinding,
    SlotInfo,
    TemplateSlideInfo,
    ThemeManifest,
)

__all__ = [
    "DEFAULT_WORKSPACE",
    "ENTRY_POINT_GROUPS",
    "PLUGIN_API_VERSION",
    "SPEC_VERSION",
    "AgenError",
    "AggregateSpec",
    "AggregationPlugin",
    "BlobStore",
    "BlockContext",
    "BlockData",
    "BlockPlugin",
    "BlockSpec",
    "BlockTarget",
    "CastIssue",
    "ColumnProfile",
    "ColumnSnapshot",
    "ColumnSpec",
    "CoverageCell",
    "CoverageReport",
    "CoverageState",
    "DType",
    "DataNeeds",
    "DatasetSpec",
    "DateSpan",
    "EngineResult",
    "ErrorCode",
    "ExpressionTools",
    "Geometry",
    "GroupBySpec",
    "HistoryManifest",
    "HistoryProvider",
    "IngestRequest",
    "IngestResult",
    "InputSpec",
    "Issue",
    "IssueLevel",
    "LayoutInfo",
    "LayoutRole",
    "MetadataStore",
    "MetricSpec",
    "NoParams",
    "NodeKind",
    "NodeState",
    "NodeStatus",
    "OverlapPolicy",
    "ParamsPlugin",
    "Period",
    "PeriodFrom",
    "PeriodUnit",
    "PlaceholderInfo",
    "Plugin",
    "PluginInfo",
    "PluginKind",
    "PluginManifest",
    "PluginStatus",
    "ProgressCallback",
    "ReadOptions",
    "ReadProgress",
    "ReaderPlugin",
    "ReconcileResult",
    "ReconcileStatus",
    "RenderResult",
    "RoleBinding",
    "RunRequest",
    "RunResult",
    "SampleTable",
    "ScenarioSpec",
    "SchemaSnapshot",
    "SlideSpec",
    "SlotInfo",
    "SortSpec",
    "SourceRecord",
    "SourceSpec",
    "SourceVersionRecord",
    "StepContext",
    "StepPlugin",
    "StepSpec",
    "TemplateSlideInfo",
    "ThemeManifest",
    "UploadRecord",
    "UploadRef",
    "UploadResult",
    "UploadStatus",
    "ValueCount",
    "WindowPlugin",
    "WindowSpec",
]
