"""Контракты Autogenerator: модели данных и интерфейсы, через которые общаются модули.

Пакет не содержит логики обработки и не зависит от других модулей приложения.
"""

from .errors import AgenError, ErrorCode
from .history import HistoryManifest, HistoryProvider, UploadRef
from .jobs import RunRequest
from .periods import DateSpan, Period, PeriodUnit
from .plugins import (
    ENTRY_POINT_GROUPS,
    PLUGIN_API_VERSION,
    AggregationPlugin,
    BlockContext,
    BlockData,
    BlockPlugin,
    BlockTarget,
    DataNeeds,
    ExpressionTools,
    NoParams,
    ParamsPlugin,
    Plugin,
    PluginInfo,
    PluginKind,
    PluginManifest,
    PluginStatus,
    ReaderPlugin,
    StepContext,
    StepPlugin,
    WindowPlugin,
)
from .results import (
    EngineResult,
    Issue,
    IssueLevel,
    NodeKind,
    NodeState,
    NodeStatus,
    RenderResult,
    RunResult,
)
from .scenario import (
    SPEC_VERSION,
    AggregateSpec,
    BlockSpec,
    DatasetSpec,
    GroupBySpec,
    InputSpec,
    MetricSpec,
    ScenarioSpec,
    SlideSpec,
    SortSpec,
    StepSpec,
    WindowSpec,
)
from .snapshot import (
    CastIssue,
    ColumnSnapshot,
    ReconcileResult,
    ReconcileStatus,
    SchemaSnapshot,
    UploadResult,
    UploadStatus,
)
from .sources import ColumnSpec, DType, OverlapPolicy, ReadOptions, SourceSpec
from .theme import (
    Geometry,
    LayoutInfo,
    LayoutRole,
    PlaceholderInfo,
    RoleBinding,
    SlotInfo,
    TemplateSlideInfo,
    ThemeManifest,
)

__all__ = [
    "ENTRY_POINT_GROUPS",
    "PLUGIN_API_VERSION",
    "SPEC_VERSION",
    "AgenError",
    "AggregateSpec",
    "AggregationPlugin",
    "BlockContext",
    "BlockData",
    "BlockPlugin",
    "BlockSpec",
    "BlockTarget",
    "CastIssue",
    "ColumnSnapshot",
    "ColumnSpec",
    "DType",
    "DataNeeds",
    "DatasetSpec",
    "DateSpan",
    "EngineResult",
    "ErrorCode",
    "ExpressionTools",
    "Geometry",
    "GroupBySpec",
    "HistoryManifest",
    "HistoryProvider",
    "InputSpec",
    "Issue",
    "IssueLevel",
    "LayoutInfo",
    "LayoutRole",
    "MetricSpec",
    "NoParams",
    "NodeKind",
    "NodeState",
    "NodeStatus",
    "OverlapPolicy",
    "ParamsPlugin",
    "Period",
    "PeriodUnit",
    "PlaceholderInfo",
    "Plugin",
    "PluginInfo",
    "PluginKind",
    "PluginManifest",
    "PluginStatus",
    "ReadOptions",
    "ReaderPlugin",
    "ReconcileResult",
    "ReconcileStatus",
    "RenderResult",
    "RoleBinding",
    "RunRequest",
    "RunResult",
    "ScenarioSpec",
    "SchemaSnapshot",
    "SlideSpec",
    "SlotInfo",
    "SortSpec",
    "SourceSpec",
    "StepContext",
    "StepPlugin",
    "StepSpec",
    "TemplateSlideInfo",
    "ThemeManifest",
    "UploadRef",
    "UploadResult",
    "UploadStatus",
    "WindowPlugin",
    "WindowSpec",
]
