// Подписи значений перечислений — так, как их видит пользователь.

export const DTYPES: Record<string, string> = {
  string: "текст",
  int: "целое число",
  float: "число",
  date: "дата",
  datetime: "дата и время",
  bool: "да/нет",
};

export const PERIOD_UNITS: Record<string, string> = {
  day: "день",
  week: "неделя",
  month: "месяц",
  quarter: "квартал",
  year: "год",
  range: "произвольный диапазон",
};

export const OVERLAP: Record<string, { label: string; hint: string }> = {
  replace_period: { label: "заменить период", hint: "строки нового файла заменяют прежние за те же даты" },
  merge_dedupe: { label: "объединить по ключам", hint: "строки с теми же ключами заменяются, новые добавляются" },
  append: { label: "добавить", hint: "строки добавляются к прежним; возможен двойной учёт" },
  replace_all: { label: "заменить всё", hint: "вся прежняя история источника выключается" },
  ask: { label: "спрашивать", hint: "при каждой загрузке с пересечением" },
};

export const UPLOAD_STATUS: Record<string, { label: string; color: string }> = {
  active: { label: "в истории", color: "teal" },
  needs_review: { label: "на проверке", color: "yellow" },
  excluded: { label: "исключена", color: "gray" },
};

export const RUN_STATUS: Record<string, { label: string; color: string }> = {
  running: { label: "идёт", color: "blue" },
  ok: { label: "собран", color: "teal" },
  errors: { label: "собран с пометками", color: "yellow" },
  failed: { label: "не собран", color: "red" },
  interrupted: { label: "прерван", color: "gray" },
};

export const options = (m: Record<string, string | { label: string }>) =>
  Object.entries(m).map(([value, v]) => ({ value, label: typeof v === "string" ? v : v.label }));

export const LAYOUT_ROLES: Record<string, string> = {
  title: "титульный",
  section: "раздел",
  title_and_content: "заголовок и объект",
  title_and_two_content: "заголовок и два объекта",
  title_text_and_content: "заголовок, текст и объект",
  title_only: "только заголовок",
  blank: "пустой",
  final: "финальный",
};

/** Подписи полей сценария и параметров модулей (в схемах названия полей — английские). */
export const FIELD_LABELS: Record<string, string> = {
  id: "id",
  label: "Подпись",
  name: "Название",
  type: "Вид",
  source: "Источник",
  main: "Основной вход",
  input: "Вход",
  inputs: "Входы и наборы",
  dataset: "Набор данных",
  metric: "Показатель",
  window: "Окно данных",
  where: "Условие",
  group_by: "Группировка",
  aggregate: "Агрегаты",
  columns: "Столбцы",
  column: "Столбец",
  compare: "Сравнение периодов",
  derive: "Расчёты",
  sort: "Сортировка",
  top: "Топ-N",
  others: "«Прочие»",
  pivot: "Сводная по столбцу",
  query: "Запрос SQL",
  code: "Код Python",
  frame: "Таблицы в коде",
  fn: "Функция",
  formula: "Формула",
  bucket: "Шаг дат",
  as: "Имя результата",
  suffix: "Окончание",
  desc: "По убыванию",
  expr: "Выражение",
  layout: "Макет",
  example: "Слайд шаблона",
  enabled: "Включён",
  markers: "Метки",
  blocks: "Блоки",
  keep: "Оставить",
  slot: "Область макета",
  shape: "Фигура",
  theme: "Шаблон",
  output_name: "Имя файла",
  relative_to: "Относительные периоды от",
  by: "Столбцы",
  how: "Как объединять",
  with: "С каким входом",
  on: "Ключи",
  drop: "Удалить столбцы",
  conditions: "Условия",
  combine: "Сочетание условий",
  op: "Операция",
  value: "Значение",
  start: "С",
  end: "По",
  last: "Последние",
  n: "Периодов",
  mode: "Режим",
  pandas_types: "Типы pandas",
  timeout: "Ограничение времени, с",
  adds: "Добавляет столбцы",
  uses: "Использует столбцы",
  cache: "Кэшировать",
  formats: "Форматы дат",
  chart: "Тип графика",
  x: "Категории (ось X)",
  categories: "Категории",
  series: "Серии",
  series_from: "Серии из данных",
  groups: "Группы серий",
  category_format: "Формат категорий",
  expected_categories: "Ожидаемые категории",
  max_points: "Секторов не больше",
  max_categories: "Категорий не больше",
  labels: "Подписи",
  legend: "Легенда",
  data_labels: "Подписи данных",
  number_format: "Формат чисел",
  pattern: "Формат дат",
  date_format: "Формат дат",
  text: "Текст",
  font_size: "Размер шрифта",
  min_font_size: "Наименьший шрифт",
  bold: "Жирный",
  align: "Выравнивание",
  header: "Заголовок",
  format: "Формат",
  number: "Формат чисел",
  max_rows: "Строк не больше",
  fixed_columns: "Постоянные столбцы",
  other_columns: "Остальные столбцы",
  heatmap: "Тепловая карта",
  fill: "Заливка",
  colors: "Цвета",
  min: "Наименьшее",
  max: "Наибольшее",
  scale: "Масштаб",
  decimals: "Знаков после запятой",
  sign: "Знак «+»",
  percent: "Доля в процентах",
  points: "Процентные пункты",
  unit: "Единица",
  capital: "С заглавной буквы",
  empty: "Если значения нет",
  color: "Цвет по знаку",
  positive: "Положительное",
  negative: "Отрицательное",
  zero: "Ноль",
  period: "Переменная периода",
  bindings: "Привязки",
  common: "Общие привязки",
  order: "Порядок",
  kind: "Вид",
  title: "Заголовок",
  bottom: "Снизу",
  depth: "Глубина",
  output: "Результат",
};
